### ISSUE TITLE
Keyboard Events Aren't Blocked On Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [wmhilton/lock-screen#3]
I used it on my Windows 10 PC. It was able to block mouse clicks. However, whenever I press any key,, it redirects me to the lock screen of Windows.

Also, Avast Antivirus is blocking it form running !!!!!

**Comment by billiegoose** [comment]
I'm guessing you didn't compile it from source then. :) The README and the latest downloadable "release" are out of sync. I'll publish a new release in the morning.

And good for Avast! I'd block a program that took control of the screen, mouse, and keyboard too. They probably are suspicious of this program because it is not downloaded very often.

**Comment by billiegoose** [comment]
(I'm closing this since I released the newer release that has the keyboard blocking feature.)
