### ISSUE TITLE
Not compatible with DisplayFusion on multiple displays

### ISSUE THREAD

**Issue by GrowingDark** [wmhilton/lock-screen#4]
I'm using this on Windows 7 and am loving it. It works great for what I need. There's only one small issue, I am running a triple monitor setup with DisplayFusion, which gives me separate taskbars for each monitor. The lock screen does block mouse clicks and the keyboard on all three desktops and the main monitor taskbar, but the two additional task bars I am able to click on and look at currently open programs.

It's not a huge deal, I can probably make a script that disables those taskbars when I run the screen saver. I just wanted to see if there was an easy fix to make it work natively.

**Comment by billiegoose** [comment]
Hmm. That's tough. It's hard to say because I don't really know how Display Fusion does the extra taskbars. I used to use Display Fusion with my triple monitor setup too, and even with auto-hide it would still cover up part of YouTube and other full-screen apps. Since Windows 10 natively supports separate taskbars per monitor I've quit using Display Fusion, so I've no easy way to test your situation. I think your best bet is definitely to use Display Fusion's scripting ability to hide the taskbars after a certain amount of time or something like that.

**Comment by billiegoose** [comment]
I should add that I wouldn't recommend upgrading to Windows 10 in your case because my screensaver doesn't work correctly in Windows 10 (see #2)

**Comment by GrowingDark** [comment]
Thank you for the fast response! I figured as much, but just thought I'd ask. I ended up making a script that disabled the task bars and turned on your Screensaver with a keyboard shortcut and then re enabled the task bars when I hit ctrl L to unlock. It works pretty perfectly now!
